
repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: 21.4b2
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
  - id: check-yaml
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: end-of-file-fixer
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.3
  hooks:
  - id: flake8
    language_version: python3.9
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: remove-tabs
